### PR TITLE
Callback with error if error thrown due to network

### LINKED ISSUE #558: "No internet connexion" case not handled in amazon-cognito-identity-js ?
Hi,

Using Amplify Auth to sign users in, I've just run a few tests with no internet connexion (by setting Chrome to "offline"), and I noticed that the promise on Auth.signIn was not rejected properly, so catch() was never fired.

I had a proper look at the error in console:

**OPTIONS https://cognito-idp.eu-central-1.amazonaws.com/ net::ERR_INTERNET_DISCONNECTED
Uncaught (in promise) TypeError: Cannot read property 'headers' of undefined**

The second error shows that in Client.js, the fetch catch does not handle the possibility of no headers at all =>
`var code = (response.headers.get('x-amzn-errortype') || 'UnknownError').split(':')[0];`

chokes on this one, and never calls the callback with an error.
Which then does not reject the signIn promise (or any other promise for any other method that relies on this)

I assume that Client.js should check that headers are indeed received first, and if not, callback an error, so that promise based code can later handle the "No internet connection" properly. The signIn call currently fails silently, which is not good in terms of UX...

Thank you!

### PR DESCRIPTION
**Pull request by cheedep**
The Fetch API throws TyperError if there are network issues. fixes #558 #389

### CODE REVIEW

**Comment by veerabio** [comment]
Let me know if tests needs to be added to aws-amplify for this case.

File: packages/amazon-cognito-identity-js/src/Client.js [hunk 1]
```diff
@@ -55,7 +55,10 @@ export default class Client {
         };
         return callback(error);
       })
-      .catch(() => {
+      .catch(err => {
+        if (err) {
```
Comment (mlabieniec) [inline packages/amazon-cognito-identity-js/src/Client.js]: should we check here if error is actually a TypeError?

    if (err && err instanceof TypeError)

for example: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

Comment (veerabio) [reply packages/amazon-cognito-identity-js/src/Client.js]: I think that would make sense if a the callback is called with a new error with a more meaningful message. but since most clients possibly handle the same error when directly using the fetch, I thought this is better.

Comment (cheedep) [reply packages/amazon-cognito-identity-js/src/Client.js]: I think that would make sense if a the callback is called with a new error with a more meaningful message. but since most clients possibly handle the same error when directly using the fetch, I thought this is better.

Comment (cheedep) [reply packages/amazon-cognito-identity-js/src/Client.js]: I see what you mean. Should we also be checking for the error message?

Comment (mlabieniec) [reply packages/amazon-cognito-identity-js/src/Client.js]: maybe so we have a uniform approach and 1 return we could do something like:

```js
let code = 'UnknownError', error = {};

// first check if we have a service error
if ( response && response.headers && response.headers.get('x-amzn-errortype') ) {
   try {
       code = (response.headers.get('x-amz-errortype').split(':')[0];
       error = {
          code,
          name: code,
          statusCode: response.status || 0,
          message: response.status.toString(),
        };
   } catch( error ) { 
      // pass through so it doesn't get swallowed if we can't parse it 
   }
// otherwise check error
} else if ( err && instanceof TypeError ) {
    error = {
        code: err.name,
        name: err.name,
        message: err.message
    };
// finally case will return 'UnknownError'
} else {
    error = {
        code: code,
        message: code
    };
}
return callback(error);

```

Comment (cheedep) [reply packages/amazon-cognito-identity-js/src/Client.js]: I think this is much better. How about providing onRejected handler to the then and throwing an error with a better message. Example:
```javascript
fetch(this.endpoint, options)
      .then(resp => {
        response = resp;
        return resp;
      }, err => {
        // If error happens here, the request failed and if it is type error throw network error
        if (err instanceof TypeError) {
          throw new Error('Network error');
        }
        throw err;
      })
```

**Comment by cheedep** [comment]
Hi @mlabieniec , what are your thoughts about the fix?

**Comment by lukezbikowski** [comment]
👍  Any chance to merge it soon please? :-) This issue is very problematic (especially for mobile apps). There is no way to catch that error (unless I missed something)...  the only workarround we have is downgrade of amazon-cognito-identity-js ...

**Comment by stripathix** [comment]
When will this fix be live on npm?

File: packages/amazon-cognito-identity-js/src/Client.js [hunk 2]
```diff
@@ -40,6 +40,13 @@ export default class Client {
       .then(resp => {
         response = resp;
         return resp;
+      }, err => {
+        // If error happens here, the request failed
+        // if it is TypeError throw network error
+        if (err instanceof TypeError) {
+          throw new Error('Network error');
```
[the remark this answers is not in the document]
Comment (SupremeTechnopriest) [reply packages/amazon-cognito-identity-js/src/Client.js]: Throwing an error automatically returns control to the caller.  You dont need return or a branch here.
